// German words for CDNMS boards, by pack. Written for this game (not copied from Codenames' lists):
// single words, at most 11 letters, work-safe, most with two or more meanings.
export default {
  classic: [
    'Schloss', 'Bank', 'Kiefer', 'Strauß', 'Leiter', 'Ball', 'Birne', 'Mutter', 'Läufer', 'Flügel',
    'Gericht', 'Blatt', 'Tor', 'Stamm', 'Zug', 'Note', 'Pflaster', 'Hahn', 'Kran', 'Schimmel',
    'Erde', 'Absatz', 'Bremse', 'Decke', 'Feder', 'Golf', 'Kater', 'Kette', 'Linse', 'Maus',
    'Netz', 'Pass', 'Raupe', 'Ring', 'Rock', 'Scheibe', 'Schuppen', 'Stift', 'Steuer', 'Tau',
    'Zylinder', 'Fliege', 'Schlange', 'Krone', 'Pony', 'Bart', 'Bauer', 'Dame', 'Turm', 'Kiwi',
    'Ente', 'Gabel', 'Hörer', 'Brücke', 'Schlüssel', 'Futter', 'Schnecke', 'Star', 'Fuchs', 'Hammer',
    'Lager', 'Schalter', 'Boxer', 'Pfeife', 'Horn', 'Kamm', 'Kiel', 'Essen', 'Halle', 'Wanze',
    'Kohle', 'Schein', 'Schale', 'Kern', 'Bock', 'Barren', 'Matte', 'Wirbel', 'Strudel', 'Schirm',
    'Rolle', 'Gang', 'Becken', 'Welle', 'Quelle', 'Bogen', 'Brille', 'Kapelle', 'Zelle', 'Knopf',
    'Nadel', 'Spitze', 'Stich', 'Bube', 'Karo', 'Kreuz', 'Mantel', 'Reifen', 'Ruder', 'Hals',
    'Maulwurf', 'Grille', 'Käfer', 'Libelle', 'Muschel', 'Hecht', 'Schwalbe', 'Weide', 'Nelke', 'Mandel',
    'Melone', 'Orange', 'Zwiebel', 'Waage', 'Senf', 'Floh', 'Schild', 'Kugel', 'Nagel', 'Rost',
    'Tafel', 'Puppe', 'Schatz', 'Stollen', 'Kreisel', 'Bügel', 'Kelle', 'Schwamm', 'Block', 'Pfund',
    'Riegel', 'Schraube', 'Zange', 'Rechen', 'Fächer', 'Figur', 'Würfel', 'Kegel', 'Bett',
    'Brett', 'Latte', 'Trainer', 'Schlitten', 'Stock', 'Kamin', 'Presse', 'Mühle', 'Nest',
    'Zopf', 'Iris', 'Knöchel', 'Tasche', 'Haube', 'Schleife', 'Band', 'Gürtel', 'Anhänger', 'Drohne',
    'Wolf', 'Otter', 'Python', 'Kröte',
  ],
  everyday: [
    'Sofa', 'Kissen', 'Teppich', 'Lampe', 'Spiegel', 'Vorhang', 'Eimer', 'Kerze', 'Korb', 'Flasche',
    'Kühlschrank', 'Pfanne', 'Topf', 'Messer', 'Socke', 'Mütze', 'Pullover', 'Jacke', 'Hose', 'Kleid',
    'Stiefel', 'Geldbörse', 'Pizza', 'Brot', 'Käse', 'Butter', 'Keks', 'Nudel', 'Banane', 'Apfel',
    'Kartoffel', 'Tomate', 'Suppe', 'Zucker', 'Honig', 'Fahrrad', 'Taxi', 'Brezel', 'Waffel', 'Popcorn',
    'Schokolade', 'Wurst', 'Zahnbürste', 'Rucksack', 'Wecker', 'Badewanne', 'Flugzeug', 'Fähre', 'Kanu', 'Lastwagen',
    'Toast', 'Quark', 'Tasse',
  ],
  nature: [
    'Löwe', 'Tiger', 'Elefant', 'Giraffe', 'Zebra', 'Pinguin', 'Delfin', 'Hai', 'Krake', 'Adler',
    'Eule', 'Papagei', 'Biene', 'Spinne', 'Frosch', 'Igel', 'Hase', 'Hirsch', 'Kamel', 'Känguru',
    'Panda', 'Flamingo', 'Qualle', 'Eiche', 'Kaktus', 'Pilz', 'Moos', 'Bambus', 'Regen', 'Nebel',
    'Donner', 'Sonne', 'Wolke', 'Vulkan', 'Wüste', 'Insel', 'Strand', 'Fluss', 'Wald', 'Höhle',
    'Ozean', 'Gletscher', 'Dschungel', 'Wasserfall', 'Komet', 'Planet', 'Galaxie', 'Hagel', 'Schnee', 'Blitz',
    'Gewitter',
  ],
  places: [
    'Schule', 'Bahnhof', 'Flughafen', 'Klinik', 'Bibliothek', 'Museum', 'Bäckerei', 'Fabrik', 'Stadion', 'Theater',
    'Kino', 'Hotel', 'Pyramide', 'Palast', 'Zoo', 'Zirkus', 'Markt', 'Tunnel', 'Garage', 'Küche',
    'Dachboden', 'Garten', 'Balkon', 'Iglu', 'Zelt', 'Hütte', 'Apotheke', 'Rathaus', 'Sauna', 'Paris',
    'London', 'Berlin', 'Hamburg', 'Venedig', 'Tokio', 'Ägypten', 'Italien', 'Japan', 'Australien', 'Spanien',
    'Hawaii', 'Sahara', 'Atlantis', 'Antarktis', 'Hollywood', 'Mond', 'Wien', 'Amsterdam', 'Alpen', 'Nordpol',
    'Schweiz', 'Mallorca', 'Nordsee', 'Rom',
  ],
  office: [
    'Drucker', 'Kaffee', 'Meeting', 'Mail', 'Pause', 'Chef', 'Akte', 'Stempel', 'Server', 'Ordner',
    'Laptop', 'Tastatur', 'Locher', 'Büroklammer', 'Kalender', 'Termin', 'Budget', 'Bericht', 'Rechnung', 'Gehalt',
    'Urlaub', 'Kollege', 'Praktikant', 'Kantine', 'Kunde', 'Projekt', 'Team', 'Tabelle', 'Headset', 'Telefon',
    'Schredder', 'Archiv', 'Agenda', 'Textmarker', 'Kuli', 'Schere', 'Feierabend', 'Konferenz', 'Beamer', 'Kopierer',
    'Pinnwand', 'Flipchart', 'Deadline',
  ],
  culture: [
    'Pirat', 'Ritter', 'Vampir', 'Zauberer', 'Drache', 'Roboter', 'Ninja', 'Gespenst', 'Mumie', 'Riese',
    'Zwerg', 'Elfe', 'Hexe', 'Troll', 'Prinzessin', 'König', 'Wikinger', 'Pharao', 'Samurai', 'Cowboy',
    'Detektiv', 'Spion', 'Astronaut', 'Superheld', 'Clown', 'Gitarre', 'Klavier', 'Geige', 'Harfe', 'Oper',
    'Konzert', 'Jazz', 'Disco', 'Karaoke', 'Flöte', 'Film', 'Western', 'Kamera', 'Schach', 'Puzzle',
    'Rätsel', 'Quiz', 'Bingo', 'Labyrinth', 'Tennis', 'Marathon', 'Pokal', 'Dinosaurier', 'Thron', 'Schwert',
    'Zauberstab', 'Domino', 'Komödie',
  ],
};
