// English words for CDNMS boards, by pack. Written for this game (not copied from Codenames' lists):
// single words, at most 11 letters, work-safe, most with two or more meanings.
export default {
  classic: [
    'bank', 'bat', 'bark', 'bow', 'crane', 'date', 'fan', 'jam', 'match', 'mint',
    'organ', 'palm', 'pitch', 'plate', 'rock', 'scale', 'seal', 'spring', 'star', 'trunk',
    'watch', 'wave', 'bolt', 'bridge', 'cell', 'chest', 'club', 'cross', 'deck', 'draft',
    'file', 'fly', 'glass', 'iron', 'key', 'lead', 'light', 'mole', 'nail', 'note',
    'pass', 'pipe', 'press', 'ruler', 'server', 'shell', 'space', 'spot', 'square', 'stamp',
    'stick', 'table', 'tie', 'track', 'trip', 'tube', 'bass', 'bill', 'boot', 'bug',
    'cape', 'capital', 'chip', 'coach', 'cone', 'court', 'cricket', 'crown', 'cup', 'diamond',
    'dish', 'drill', 'duck', 'fall', 'fork', 'hand', 'heart', 'hide', 'hood', 'horn',
    'jack', 'jet', 'kid', 'kite', 'letter', 'lock', 'log', 'mouse', 'mug', 'nut',
    'orange', 'page', 'park', 'pine', 'pole', 'pool', 'post', 'pound', 'punch', 'pupil',
    'racket', 'record', 'rose', 'saw', 'school', 'screen', 'shed', 'sink', 'slug', 'sole',
    'spade', 'speaker', 'staff', 'straw', 'suit', 'swallow', 'tank', 'toast', 'wing', 'yard',
    'band', 'bench', 'bulb', 'calf', 'case', 'china', 'cloud', 'coat', 'copper', 'flat',
    'foot', 'frame', 'green', 'gum', 'honey', 'horse', 'jumper', 'kiwi', 'knot', 'lemon',
    'lime', 'marble', 'mercury', 'monitor', 'pilot', 'plant', 'present', 'pump', 'queen', 'robin',
    'roll', 'skate', 'switch', 'tip', 'train', 'well', 'yarn', 'boxer', 'lift',
  ],
  everyday: [
    'kettle', 'sofa', 'pillow', 'blanket', 'lamp', 'mirror', 'curtain', 'ladder', 'bucket', 'broom',
    'sponge', 'towel', 'soap', 'candle', 'basket', 'bottle', 'fridge', 'oven', 'spoon', 'knife',
    'sock', 'glove', 'scarf', 'sweater', 'shirt', 'umbrella', 'wallet', 'pizza', 'bread', 'cheese',
    'cookie', 'pasta', 'banana', 'carrot', 'potato', 'tomato', 'soup', 'sugar', 'bicycle', 'taxi',
    'truck', 'scooter', 'tram', 'helmet', 'sandwich', 'noodle', 'slipper', 'backpack', 'toothbrush', 'waffle',
    'popcorn', 'chocolate',
  ],
  nature: [
    'lion', 'tiger', 'elephant', 'giraffe', 'zebra', 'penguin', 'dolphin', 'whale', 'shark', 'octopus',
    'eagle', 'owl', 'parrot', 'bee', 'spider', 'frog', 'snake', 'turtle', 'rabbit', 'fox',
    'wolf', 'deer', 'camel', 'kangaroo', 'panda', 'squirrel', 'oak', 'flower', 'cactus', 'mushroom',
    'bamboo', 'tulip', 'storm', 'thunder', 'fog', 'snow', 'frost', 'tornado', 'volcano', 'desert',
    'island', 'beach', 'river', 'forest', 'jungle', 'cave', 'ocean', 'glacier', 'comet', 'planet',
    'galaxy', 'sun',
  ],
  places: [
    'castle', 'airport', 'hospital', 'library', 'museum', 'bakery', 'factory', 'stadium', 'cinema', 'hotel',
    'restaurant', 'tower', 'pyramid', 'palace', 'farm', 'zoo', 'circus', 'market', 'tunnel', 'garage',
    'kitchen', 'attic', 'garden', 'balcony', 'station', 'igloo', 'tent', 'skyscraper', 'gym', 'fountain',
    'aquarium', 'bedroom', 'sauna', 'paris', 'rome', 'london', 'berlin', 'venice', 'tokyo', 'egypt',
    'italy', 'japan', 'mexico', 'australia', 'iceland', 'hawaii', 'sahara', 'everest', 'moon', 'hollywood',
    'atlantis', 'antarctica',
  ],
  office: [
    'printer', 'coffee', 'meeting', 'email', 'deadline', 'desk', 'chair', 'stapler', 'folder', 'laptop',
    'calendar', 'budget', 'boss', 'report', 'memo', 'invoice', 'whiteboard', 'pencil', 'scissors', 'paperclip',
    'envelope', 'badge', 'contract', 'salary', 'vacation', 'lunch', 'canteen', 'colleague', 'manager', 'client',
    'project', 'team', 'spreadsheet', 'chart', 'backup', 'download', 'headset', 'webcam', 'phone', 'shredder',
    'calculator', 'copier',
  ],
  culture: [
    'pirate', 'knight', 'vampire', 'wizard', 'dragon', 'robot', 'ninja', 'ghost', 'mummy', 'mermaid',
    'unicorn', 'giant', 'dwarf', 'fairy', 'prince', 'viking', 'pharaoh', 'samurai', 'cowboy', 'detective',
    'spy', 'astronaut', 'superhero', 'clown', 'guitar', 'piano', 'violin', 'trumpet', 'drum', 'opera',
    'concert', 'ballet', 'jazz', 'disco', 'karaoke', 'movie', 'cartoon', 'western', 'camera', 'chess',
    'puzzle', 'dice', 'domino', 'quiz', 'soccer', 'tennis', 'golf', 'trophy', 'treasure', 'throne',
    'sword', 'potion', 'wand', 'dinosaur',
  ],
};
